binder_chain: B
design_algorithm: 3stages
disconnect_feats: true
disconnect_pairformer: false
distogram_only: true
e_soft: 0.8
e_soft_1: 0.8
e_soft_2: 1.0
hard_iteration: 5
helix_loss_max: -0.0
helix_loss_min: -0.3
increasing_contact_over_itr: false
inter_chain_cutoff: 20.0
intra_chain_cutoff: 14.0
learning_rate: 0.1
learning_rate_pre: 1.0
length_max: 170
length_min: 90
mask_ligand: false
msa_max_seqs: 4096
non_protein_target: false
num_inter_contacts: 2
num_intra_contacts: 2
optimize_contact_per_binder_pos: true
optimizer_type: SGD
pocket_conditioning: true
pre_iteration: 30
semi_greedy_steps: 2
set_train: true
soft_iteration: 80
soft_iteration_1: 50
soft_iteration_2: 50
temp_iteration: 45
use_temp: true
recycling_steps: 0
noise_scaling: 0.1